-- MySQL Script generated by MySQL Workbench
-- 10/27/17 10:58:51
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema agronevada
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `agronevada` ;

-- -----------------------------------------------------
-- Schema agronevada
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `agronevada` DEFAULT CHARACTER SET utf8 ;
USE `agronevada` ;

-- -----------------------------------------------------
-- Table `agronevada`.`tipoCafe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agronevada`.`tipoCafe` (
  `idTipoCafe` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  `precioKg` FLOAT NOT NULL,
  `bonificacion` FLOAT NULL,
  PRIMARY KEY (`idTipoCafe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agronevada`.`tipoSecado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agronevada`.`tipoSecado` (
  `idTipoSecado` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoSecado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agronevada`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agronevada`.`clientes` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `cedula` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `cedula_UNIQUE` (`cedula` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agronevada`.`productores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agronevada`.`productores` (
  `idProductor` INT NOT NULL AUTO_INCREMENT,
  `nombreFinca` VARCHAR(45) NOT NULL,
  `nombreGerente` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProductor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agronevada`.`conductores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agronevada`.`conductores` (
  `idConductor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NULL,
  PRIMARY KEY (`idConductor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agronevada`.`lotes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agronevada`.`lotes` (
  `idLote` INT NOT NULL AUTO_INCREMENT,
  `productores_id` INT NOT NULL,
  `conductores_id` INT NOT NULL,
  `tipoCafe_idTipoCafe` INT NOT NULL,
  `tipoSecado_idTipoSecado` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `cantidadKg` FLOAT NOT NULL,
  `factorRendimiento` FLOAT NOT NULL,
  `humedad` FLOAT NOT NULL,
  `pruebaTaza` FLOAT NOT NULL,
  `precioBase` FLOAT NOT NULL,
  `saldo` FLOAT NOT NULL,
  `descuento` FLOAT NOT NULL,
  `retefuente` FLOAT NULL,
  `bonificacion` FLOAT NULL,
  PRIMARY KEY (`idLote`),
  INDEX `fk_llegadas_productores_idx` (`productores_id` ASC),
  INDEX `fk_llegadas_conductores1_idx` (`conductores_id` ASC),
  INDEX `fk_lotes_tipoCafe1_idx` (`tipoCafe_idTipoCafe` ASC),
  INDEX `fk_lotes_tipoSecado1_idx` (`tipoSecado_idTipoSecado` ASC),
  UNIQUE INDEX `idLote_UNIQUE` (`idLote` ASC),
  CONSTRAINT `fk_llegadas_productores`
    FOREIGN KEY (`productores_id`)
    REFERENCES `agronevada`.`productores` (`idProductor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_llegadas_conductores1`
    FOREIGN KEY (`conductores_id`)
    REFERENCES `agronevada`.`conductores` (`idConductor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lotes_tipoCafe1`
    FOREIGN KEY (`tipoCafe_idTipoCafe`)
    REFERENCES `agronevada`.`tipoCafe` (`idTipoCafe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lotes_tipoSecado1`
    FOREIGN KEY (`tipoSecado_idTipoSecado`)
    REFERENCES `agronevada`.`tipoSecado` (`idTipoSecado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agronevada`.`ajustes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agronevada`.`ajustes` (
  `idAjuste` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  `fecha` DATE NOT NULL,
  `cantidadkg` FLOAT NOT NULL,
  `llegadas_id` INT NOT NULL,
  PRIMARY KEY (`idAjuste`),
  INDEX `fk_ajustes_llegadas1_idx` (`llegadas_id` ASC),
  CONSTRAINT `fk_ajustes_llegadas1`
    FOREIGN KEY (`llegadas_id`)
    REFERENCES `agronevada`.`lotes` (`idLote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agronevada`.`salidas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agronevada`.`salidas` (
  `idSalida` INT NOT NULL AUTO_INCREMENT,
  `direccionDespacho` VARCHAR(45) NOT NULL,
  `fecha` DATE NOT NULL,
  `clientes_id` INT NOT NULL,
  PRIMARY KEY (`idSalida`),
  INDEX `fk_salidas_clientes1_idx` (`clientes_id` ASC),
  CONSTRAINT `fk_salidas_clientes1`
    FOREIGN KEY (`clientes_id`)
    REFERENCES `agronevada`.`clientes` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agronevada`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agronevada`.`roles` (
  `idroles` INT NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idroles`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agronevada`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agronevada`.`usuarios` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(70) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `contrasena` VARCHAR(45) NOT NULL,
  `roles_idroles` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_usuarios_roles1_idx` (`roles_idroles` ASC),
  CONSTRAINT `fk_usuarios_roles1`
    FOREIGN KEY (`roles_idroles`)
    REFERENCES `agronevada`.`roles` (`idroles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agronevada`.`configuracion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agronevada`.`configuracion` (
  `idConfiguracion` INT NOT NULL AUTO_INCREMENT,
  `descuento` FLOAT NOT NULL,
  `retefuente` FLOAT NOT NULL,
  `baseRetefuente` FLOAT NOT NULL,
  PRIMARY KEY (`idConfiguracion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agronevada`.`auditorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agronevada`.`auditorias` (
  `idAuditoria` INT NOT NULL AUTO_INCREMENT,
  `tipoTransaccion` CHAR NOT NULL,
  `tabla` VARCHAR(45) NOT NULL,
  `pk` INT NOT NULL,
  `campo` VARCHAR(45) NULL,
  `valorOriginal` VARCHAR(100) NULL,
  `valorNuevo` VARCHAR(45) NULL,
  `fecha` DATETIME NOT NULL,
  `usuarios_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idAuditoria`),
  INDEX `fk_auditorias_usuarios1_idx` (`usuarios_idUsuario` ASC),
  CONSTRAINT `fk_auditorias_usuarios1`
    FOREIGN KEY (`usuarios_idUsuario`)
    REFERENCES `agronevada`.`usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agronevada`.`lotes_has_salidas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agronevada`.`lotes_has_salidas` (
  `lotes_idLote` INT NOT NULL,
  `salidas_idSalida` INT NOT NULL,
  `cantidad` FLOAT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`, `lotes_idLote`, `salidas_idSalida`),
  INDEX `fk_lotes_has_salidas_salidas1_idx` (`salidas_idSalida` ASC),
  INDEX `fk_lotes_has_salidas_lotes1_idx` (`lotes_idLote` ASC),
  CONSTRAINT `fk_lotes_has_salidas_lotes1`
    FOREIGN KEY (`lotes_idLote`)
    REFERENCES `agronevada`.`lotes` (`idLote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lotes_has_salidas_salidas1`
    FOREIGN KEY (`salidas_idSalida`)
    REFERENCES `agronevada`.`salidas` (`idSalida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
